CREATE DATABASE NaverSEO_example;

show databases;

use NaverSEO_example;

CREATE TABLE 브랜드 (
    브랜드ID INT PRIMARY KEY AUTO_INCREMENT,
    브랜드명 VARCHAR(255) NOT NULL
);

CREATE TABLE 제품 (
    제품ID INT PRIMARY KEY AUTO_INCREMENT,
    브랜드ID INT NOT NULL,
    제품명 VARCHAR(255) NOT NULL,
    FOREIGN KEY (브랜드ID) REFERENCES 브랜드(브랜드ID)
);

CREATE TABLE 키워드 (
    키워드ID INT PRIMARY KEY AUTO_INCREMENT,
    제품ID INT NOT NULL,
    키워드 VARCHAR(255) NOT NULL,
    FOREIGN KEY (제품ID) REFERENCES 제품(제품ID)
);

CREATE TABLE 항목 (
    항목ID INT PRIMARY KEY AUTO_INCREMENT,
    키워드ID INT NOT NULL,
    항목명 VARCHAR(255) NOT NULL,
    날짜 DATE,
    FOREIGN KEY (키워드ID) REFERENCES 키워드(키워드ID)
);

